### PR TITLE
Cleaned up obsolete usage warnings and orphaned meta files

### PR DESCRIPTION
**Pull request by wcoastsands**
Obsolete usage warnings occur in Unity 4 and newer. Changes are wrapped with preprocessor directives so they won't affect Unity versions 3.5.x. Among these commits is also a fix for exporting the Examples packages: Unity was failing to included dependent DLLs and base classes.

### CODE REVIEW

**Comment by frarees** [comment]
:+1:

**Comment by tgraupmann** [comment]
It looks like you upgraded NGUI as well. Is it still compatible with Unity 3.5.7? I have to use the free distribution version.

**Comment by wcoastsands** [comment]
I haven't tested against 3.5 yet. Didn't think it was still being supported. I'm using version 4.2.0f4 with a trial license. Is 3.5.7 the baseline you're looking to support? Also fixed a dependency issue with the Example package export. For some reason Unity isn't pickup the DLLs or base classes in NGUI when building the package. So I included the directories for them in the export process as a fix.

**Comment by tgraupmann** [comment]
Unity 3.5.7 is my base line. Apparently only 5% of Unity developers are still on 3.5.7. Package export is supposed to find dependencies, I'll add your changes to find the missing DLLs.

**Comment by wcoastsands** [comment]
Sounds good. I'll run a test on 3.5.7 later this evening. If it turns out the changes aren't supported, I'll wrap them within compile time conditionals for the two versions of Unity.

**Comment by wcoastsands** [comment]
Wrapped updates for Unity version 4 and newer with preprocessor directives so changes don't affect 3.5.x. Tested in both Unity 3.5.7 and 4.2.0. The diff is a little messy for a few files since line endings were converted. Let me know if you want me to redo those before merging. Otherwise, everything looks good.

**Comment by frarees** [comment]
I won't touch NGUI at all in this package. That cleanup could be done directly on their code (NGUI), not here, IMO. What do you think?

**Comment by wcoastsands** [comment]
I'd actually prefer that as well. Any idea where to get an updated redistributable version that also supports 3.5.7?

**Comment by frarees** [comment]
I think the latest NGUI version (2.6.4 as of today) supports 3.5+. They however dropped support for 3.4.  Downloadable [here](http://www.tasharen.com/get.php?file=NGUIDistro). 

Quoting from Tasharen website: 

> Please note that NGUI requires the latest version of Unity 3.5 or 4. As of this writing this means Unity 3.5.7, and 4.1+. You can get it to work with versions as early as 3.4.2, but it will require work on your part.

**Comment by wcoastsands** [comment]
Thanks for the link. So that distribution package still throws 24 obsolete usage warnings. I checked the free edition as well; 33 warnings there. Looks like we might just have to live with it for now. I'm going to revert that commit and just clean up the ones outside NGUI.

**Comment by tgraupmann** [comment]
You have to upgrade to Unity 4.X if you want the latest and greatest for NGUI.

**Comment by frarees** [comment]
Probably the greatest, but not the latest. AFAIK NGUI 2.6.4 works on Unity 3.5.7. Have you tried it on 3.5.7 and is not working properly?

**Comment by tgraupmann** [comment]
Right 2.6.4 is available for Unity 3.5.7.

And the distribution version is available here - http://www.tasharen.com/?page_id=140

**Comment by tgraupmann** [comment]
These changes look decent if there's a way to ignore the NGUI part. You may need to submit a separate pull request.

**Pull request closed without merging**
